version: "3.3"

services:

  db:
    container_name: udemy_django2
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/.MySql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "udemy"
      MYSQL_DATABASE: "udemy_django2"
    ports:
      - 3306:3306
